### ISSUE TITLE
No limpia total diario al pasar al siguiente día

### ISSUE THREAD

**Issue by provirabosch** [funEBunny/XPDroid#11]
No limpia total diario si se apaga el celular

**Comment by aschmidt7** [comment]
No pude reproducir el issue, lo dejamos abierto para monitoreo

**Comment by provirabosch** [comment]
@aschmidt7 volvió a fallar. Me sumó para el total diario los gastos de 2 días diferentes.

**Comment by aschmidt7** [comment]
@provirabosch vamos a tener que hacer algo para loguear, y tatar de entender como reproducirlo, como tenias hechos los gastos?

**Comment by provirabosch** [comment]
@aschmidt7 Ayer instalé la app de nuevo. Cargué 2 gastos: uno con fecha 14/09 y otro con fecha 16/09. Hoy que es 15/09 debería estar el total en $0, pero me sumó esos 2 gastos como total diario de hoy.

**Comment by aschmidt7** [comment]
Había un error en el método de obtener gastos por dia y estaba devolviendo cualquier cosa.
Hice el fix. Hay que probarlo

**Comment by provirabosch** [comment]
Ok, reinstalo y mañana veo.

**Comment by provirabosch** [comment]
@aschmidt7 grosooo quedó bien! Lo cierro.

**Comment by provirabosch** [comment]
@aschmidt7 para cuando Alina te deje...me volvió a fallar esto.
![screenshot_2015-09-19-07-57-53](https://cloud.githubusercontent.com/assets/11699240/9975931/10a9d06c-5ea5-11e5-96a1-2a403e74b39f.png)
![screenshot_2015-09-19-07-58-18](https://cloud.githubusercontent.com/assets/11699240/9975932/10aa4b6e-5ea5-11e5-9605-ed888427f8be.png)

**Comment by provirabosch** [comment]
@funEBunny/owners limpió bien hoy domingo total diario y total semanal
dejo el issue abierto para seguir controlando
