### ISSUE TITLE
Boton Back

### ISSUE THREAD

**Issue by akawakita** [funEBunny/XPDroid#16]
Comportamiento Actual:
Estando en cualquier opcion directa desde el menu (Historial, Favoritos, Programables, Presupuesto, Totales, etc), al presionar el boton "Volver" de Android la aplicacion sale de la vista. Y vuelve al sistema operativo del dispositivo.

Comportamiento Deseado:
Estando en cualquier opcion directa desde el menu (Historial, Favoritos, Programables, Presupuesto, Totales, etc) salvo en Inicio, al presionar el boton "Volver" de Android la aplicacion debe volver a la pagina de Inicio. 

Mejoras:
1) Comodidad en la navegacion
2) Acceso rapido a la pagina de Inicio
3) No se sale de la apliacion por equivocacion

**Comment by provirabosch** [comment]
Terminado
