### ISSUE TITLE
Test ServicioHistorialBusiness

### ISSUE THREAD

**Issue by provirabosch** [funEBunny/XPDroid#29]

**Comment by provirabosch** [comment]
@aschmidt7 para desinstalar la app antes de cada test, hay que agregar algo en la configuración Run
http://stackoverflow.com/questions/28076751/how-to-automatically-uninstall-android-app-from-device-before-installing-a-new-v

**Comment by provirabosch** [comment]
@aschmidt7 fijate que si corres todos los tests de la app juntos, a veces el método testGuardarNuevoHistorial() falla en la comparación. Ya me pasó con otras clases de test mías. Cuando las corres individualmente puede que funcionen bien, pero después cuando ejecutas todas juntas ya sea haciendo Run o con el gradlew connectedCheck, suele fallar.
Es porque la base de datos queda sucia con algún dato que se generó en otro clase de test, y te genera algún conflicto con el manejo de datos que hagas en tu clase de test.
La solución que encontré por ej, para la de servicio de presupuesto, es borrar todos los presupuestos en el método setUp.

**Comment by aschmidt7** [comment]
si el problema es que estoy haciendo una comparación con el total del historial. Voy a ver eso de borrar todo y sino voy a  sacar ese assert.

**Comment by provirabosch** [comment]
@aschmidt7 copiate de los míos! tuve varios issues de estos en la semana y tuve que hacer métodos de "limpieza". Es una cagada lo de la bas de datos pero bueno, lo arreglamos así.

**Comment by aschmidt7** [comment]
completed
