### ISSUE TITLE
No guarda gasto programable semanal en día Domingo

### ISSUE THREAD

**Issue by provirabosch** [funEBunny/XPDroid#36]
Ayer le dí bastante a los programables y encontré esto también. Si guardas un gasto semanal en Domingo, te lo guarda como Sábado. Me parece que es por esto: (ver imágenes)

![2015-10-25_08-53-55](https://cloud.githubusercontent.com/assets/11699240/10715459/5f56db98-7af6-11e5-8322-0f5b09a6098f.png)
![2015-10-25_08-55-05](https://cloud.githubusercontent.com/assets/11699240/10715460/5f5b77a2-7af6-11e5-8690-32652ea7326f.png)

**Comment by akawakita** [comment]
Si, esta relacionado con el #40. Lo arreglo a la noche

**Comment by akawakita** [comment]
Solucionado con el commit.
