### ISSUE TITLE
ServicioHistorialBusinessTest: exception

### ISSUE THREAD

**Issue by akawakita** [funEBunny/XPDroid#37]
Corri un gradlew connectedCheck y esta dando la siguiente Exception:

com.funebunny.xpdroid.business.historial.service.ServicioHistorialBusinessTest > testGuardarNuevoHistorial[Nexus 7 - 4.4.4] FAILED 
        junit.framework.ComparisonFailure: expected:<[8]> but was:<[9]>
        at junit.framework.Assert.assertEquals(Assert.java:85)

**Comment by provirabosch** [comment]
@akawakita ahhh por algo no me sonaba, este lo hizo @aschmidt7 !
Se lo paso.

**Comment by akawakita** [comment]
Este issue dejo de pasar magicamente, pero puede que tenga que ver con un orden de ejecucion especifico de los test (suponiendo que JUnit lo corre aleatoriamente). Hay que chequear porque a veces da 8 y otras 9. Slds!

**Comment by aschmidt7** [comment]
done
