### ISSUE TITLE
CrearGastoActivityTest: Exception

### ISSUE THREAD

**Issue by akawakita** [funEBunny/XPDroid#38]
Corri un gradlew connectedCheck y dio la siguiente Exception:

com.funebunny.xpdroid.main.ui.activity.CrearGastoActivityTest > testCrearGastoVarios[Nexus 7 - 4.4.4] FAILED 
        android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Set"
        If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:android.widget.ListView{425936b8 V
FED..C. ........ 0,95-326,373 #102000a android:id/list}

**Comment by provirabosch** [comment]
Eso es por el idioma. Como lo tengo en inglés, el botón tiene el texto "Set".

**Comment by akawakita** [comment]
Te referis al celular? Tengo que editar el test para que no me salte el error?

**Comment by provirabosch** [comment]
Claro. Es la forma de poder darle Ok al botón del Date Picker (o por lo menos, la más fácil que encontré). Fijate que texto aparece en español y cambialo. Y sino pondré mi celular en español y listo.

**Comment by akawakita** [comment]
Solucionado en el commit que hice arriba
