### ISSUE TITLE
MainActivityTest: Exception

### ISSUE THREAD

**Issue by akawakita** [funEBunny/XPDroid#39]
Luego de arreglado el #38, se corrio de vuelta gradlew y dio la siguiente excepcion:

com.funebunny.xpdroid.main.ui.activity.MainActivityTest > testProgramables[Nexus 7 - 4.4.4] FAILED 
        android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with text: is "Programables" and view has effective visibility=VISIBLE)
        If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:android.widget.ListView{42596840 I
FED.VC. ......I. -320,0-0,1087 #7f0e0089 app:id/navigation_drawer}

**Comment by provirabosch** [comment]
Cuando pasa esto, correlo enseguida de nuevo.
Es un error aleatorio y por lo que me parece a mí, tiene que ver con la velocidad que se abren y cierran las pantallas. Muchas veces pasa la primera vez que lo corres. 
Yo ayer estuve haciendo varias pruebas y no me salió nunca.

**Comment by akawakita** [comment]
Listo, lo corri y dejo de pasar. Solo queda el #37

**Comment by provirabosch** [comment]
Bien.

Ese 37 ahora lo voy a ver. Es muy parecido al que me da a mí con la
clase  ServicioGastosBusinessTest que subiste el otro día.
Cuando hiciste el gradlew no te pasó? Me salen excepciones como que no le
dan igual los valores.
Es por algo que queda sucio o que no estamos obteniendo bien el valor a
comparar. Ya me pasó con otros test la semana pasada.

**Comment by provirabosch** [comment]
Listo, no me falló! Queda lo de Chicho nomás (ServicioHistorial)
Vamos 76% según el reporte que me salió a mí.

2015-10-28 20:59 GMT-03:00 Pablo Rovira Bosch pablorovirabosch@gmail.com:

> Bien.
> 
> Ese 37 ahora lo voy a ver. Es muy parecido al que me da a mí con la
> clase  ServicioGastosBusinessTest que subiste el otro día.
> Cuando hiciste el gradlew no te pasó? Me salen excepciones como que no le
> dan igual los valores.
> Es por algo que queda sucio o que no estamos obteniendo bien el valor a
> comparar. Ya me pasó con otros test la semana pasada.
>
