### ISSUE TITLE
ServicioGastosBusiness getDiaSemana

### ISSUE THREAD

**Issue by akawakita** [funEBunny/XPDroid#40]
En el metodo 
public int getDiaSemana(String diaSemana)
Se detecto que el valor devuelto en default es SATURDAY.
Deberia ser SUNDAY?

**Comment by aschmidt7** [comment]
Si deberia ser SUNDAY.

**Comment by akawakita** [comment]
Ok, solo preguntaba para no romper nada ya hecho. Lo arreglo a la noche.

**Comment by akawakita** [comment]
Solucionado con el commit.
