### ISSUE TITLE
Formulario de Gasto Programable

### ISSUE THREAD

**Issue by provirabosch** [funEBunny/XPDroid#51]
Formulario Gastos Progamables
Campos:

Importe:
Criterio aplicados en el campo: 
1) Al seleccionar un campo numerico como Importe, aparece un teclado tactil para cargar el valor, en el cual solo se pueden seleccionar valores numericos y el punto (.) como separador de decimal.
2) El punto anterior implica que no es posible cargar valores que no sean numericos y el punto (.). Es decir, no sera posible cargar caracteres alfanumericos, caracteres especiales y valores numericos negativos.
3) El valor de punto (.) se puede cargar solo una vez y es viable cargarlo sin haber ingresado previamente la parte entera del importe.
4) La longitud maxima del importe es de 6 digitos en la parte entera y 2 digitos decimales. Ejemplo valido maximo: $999999.99
5) El campo es obligatorio.

Volumen 1:  Cargar importe de 999999.99. Criterio: 6 digitos parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $999999.99
Volumen 6:  Cargar importe de 1.11. Criterio: 1 digito parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $1.11
Volumen 7:  Cargar importe de 7654321. Criterio: 7 digitos parte entera y sin decimales. Resultado: Exitoso. Se carga hasta el importe $765432, ya que no deja cargar mas de 6 digitos en la parte entera.
Volumen 8:  Cargar importe .01. Criterio: Sin parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga como $0.01
Volumen 9:  No Cargar importe. Criterio: Sin parte entera y sin decimales. Resultado: Exitoso. Aparece una advertencia indicando que el campo es obligatorio y debe cargarse aunque sea un valor.
Volumen 10: Cargar importe 0. Criterio: 1 digito y sin digitos decimales. Resultado: Exitoso. Aparece una advertencia indicando que el campo debe cargarse con un valor mayor a 0.
Volumen 11: Cargar dos puntos (.). Criterio: Sin parte entera y sin decimales. Resultado: Exitoso. Solo deja cargar 1 punto (.)
Volumen 12: Cargar 1 punto (.). Criterio: Sin parte entera y sin decimales. Resultado: Exitoso. El valor se autocompleta y deja el importe en $0. pero sin dejar que se pueda guardar porque el valor debe ser mayor a 0.
Volumen 13: Cargar un valor alfanumerico. Resultado: Exitoso. No fue posible agregar ya que el teclado tactil permite cargar solamente valores numericos y el punto (.)
Volumen 14: Cargar un valor numerico negativo. Resultado: Exitoso. No fue posible agregar ya que el teclado tactil permite cargar solamente valores numericos y el punto (.), no existe el signo menos (-)

Categoría

Horario

Repetición

Descripción

**Comment by akawakita** [comment]
[BACKUP]

Formulario Gastos Progamables
Campos:

Importe:
Criterio aplicados en el campo: 
1) Al seleccionar un campo numerico como Importe, aparece un teclado tactil para cargar el valor, en el cual solo se pueden seleccionar valores numericos y el punto (.) como separador de decimal.
2) El punto anterior implica que no es posible cargar valores que no sean numericos y el punto (.).
3) El valor de punto (.) se puede cargar solo una vez y es viable cargarlo sin haber ingresado previamente la parte entera del importe.
4) La longitud maxima del importe es de 6 digitos en la parte entera y 2 digitos decimales. Ejemplo valido maximo: $999999.99

Volumen 1:  Cargar importe de 123456. Criterio: 6 digitos parte entera y sin decimales. Resultado: Exitoso. Se carga $123456
            Cargar importe de 123456.7. Criterio: 6 digitos parte entera y 1 digito decimal. Resultado: Exitoso. Se carga $123456.70
            Cargar importe de 999999.99. Criterio: 6 digitos parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $999999.99
Volumen 2:  Cargar importe de 55555. Criterio: 5 digitos parte entera sin decimales. Resultado: Exitoso. Se carga $55555
            Cargar importe de 55555.5. Criterio: 5 digitos parte entera y 1 digito decimal. Resultado: Exitoso. Se carga $55555.50
            Cargar importe de 55555.55. Criterio: 5 digitos parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $55555.55
Volumen 3:  Cargar importe de 4444. Criterio: 4 digitos parte entera sin decimales. Resultado: Exitoso. Se carga $4444
            Cargar importe de 4444.4. Criterio: 4 digitos parte entera y 1 digito decimal. Resultado: Exitoso. Se carga $4444.40
            Cargar importe de 4444.44. Criterio: 4 digitos parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $4444.44
Volumen 4:  Cargar importe de 333. Criterio: 3 digitos parte entera sin decimales. Resultado: Exitoso. Se carga $333
            Cargar importe de 333.3. Criterio: 3 digitos parte entera y 1 digito decimal. Resultado: Exitoso. Se carga $333.30
            Cargar importe de 333.33. Criterio: 3 digitos parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $333.33
Volumen 5:  Cargar importe de 22. Criterio: 2 digitos parte entera sin decimales. Resultado: Exitoso. Se carga $22
            Cargar importe de 22.2. Criterio: 2 digitos parte entera y 1 digito decimal. Resultado: Exitoso. Se carga $22.20
            Cargar importe de 22.22. Criterio: 2 digitos parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $22.22
Volumen 6:  Cargar importe de 1. Criterio: 1 digito parte entera sin decimales. Resultado: Exitoso. Se carga $1
            Cargar importe de 1.1. Criterio: 1 digito parte entera y 1 digito decimal. Resultado: Exitoso. Se carga $1.10
            Cargar importe de 1.11. Criterio: 1 digito parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga $1.11
Volumen 7:  Cargar importe de 7654321. Criterio: 7 digitos parte entera y sin decimales. Resultado: Exitoso. Se carga hasta el importe $765432, ya que no deja cargar mas de 6 digitos en la parte entera.
Volumen 8:  Cargar importe .01. Criterio: Sin parte entera y 2 digitos decimales. Resultado: Exitoso. Se carga como $0.01
Volumen 9:  No Cargar importe. Criterio: Sin parte entera y sin decimales. Resultado: Exitoso. Aparece una advertencia indicando que el campo es obligatorio y debe cargarse aunque sea un valor.
Volumen 10: Cargar importe 0. Criterio: 1 digito y sin digitos decimales. Resultado: Exitoso. Aparece una advertencia indicando que el campo debe cargarse con un valor mayor a 0.
Volumen 11: Cargar dos puntos (.). Criterio: Sin parte entera y sin decimales. Resultado: Exitoso. Solo deja cargar 1 punto (.)
Volumen 12: Cargar 1 punto (.). Criterio: Sin parte entera y sin decimales. Resultado: Exitoso. El valor se autocompleta y deja el importe en $0. pero sin dejar que se pueda guardar porque el valor debe ser mayor a 0.

Categoría

Horario

Repetición

Descripción
