### ISSUE TITLE
Exception al bajar codigo de backup

### ISSUE THREAD

**Issue by akawakita** [funEBunny/XPDroid#59]
Tira el siguiente error:

11-23 00:20:22.033 5983-5983/com.funebunny.xpdroid E/dalvikvm: Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzap
11-23 00:20:22.033 5983-5983/com.funebunny.xpdroid E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzb
11-23 00:20:22.103 5983-6008/com.funebunny.xpdroid E/GMPM: getGoogleAppId failed with status: 10
11-23 00:20:22.103 5983-6008/com.funebunny.xpdroid E/GMPM: Uploading is not possible. App measurement disabled
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime: FATAL EXCEPTION: main
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime: java.lang.RuntimeException: Unable to create application com.activeandroid.app.Application: android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4154)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread.access$1300(ActivityThread.java:130)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:  Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.activeandroid.Registry.openDatabase(Registry.java:149)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.activeandroid.Registry.initialize(Registry.java:107)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:8)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.activeandroid.app.Application.onCreate(Application.java:9)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
11-23 00:20:23.003 5983-5983/com.funebunny.xpdroid E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 

Adjunto Imagenes de mi SDK:
![untitled](https://cloud.githubusercontent.com/assets/11699289/11329284/c3072542-9178-11e5-8782-ffc3e24d9651.png)
![untitled2](https://cloud.githubusercontent.com/assets/11699289/11329285/c3803acc-9178-11e5-9b62-4d64db77dc33.png)

**Comment by provirabosch** [comment]
@akawakita @aschmidt7 Tienen que desinstalar la app de sus teléfonos/tablet y volverla a instalar porque le bajé el número de versión de la DB a 1.
